MPESA_CONSUMER_KEY: 'bjtLYVrV1EOhRfgIIudSMAxu9Fpe1AQz'
MPESA_CONSUMER_SECRET: 'Ti2P10VMhidPrV5J'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: '<your initiator password>'
CALLBACK_URL: "https://1fed-196-201-215-6.ngrok.io"
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
